#!/bin/bash
#SBATCH -J myMPI            # job name
#SBATCH -o myMPIScan1M.o        # output and error file name (%j expands to jobID)
#SBATCH -N 1                # number of nodes requested
#SBATCH -n 1               # total number of mpi tasks requested
#SBATCH -p normal      # queue (partition) -- normal, development, etc.
#SBATCH -t 01:30:00         # run time (hh:mm:ss) - 1.5 hours

# Slurm email notifications are now working on Lonestar 5 
#SBATCH --mail-user=chyacinthz@gmail.com
#SBATCH --mail-type=begin   # email me when the job starts
#SBATCH --mail-type=end     # email me when the job finishes

# run the executable named a.out
# 1 core, 1 socket, 1 node
ibrun numactl -C 13 ./a.out 1000000
ibrun numactl -N 0 ./a.out 1000000
ibrun numactl ./a.out 1000000